---
# We've potentially updated the kernel or params,
# so let's check if we need to reboot just to be safe...
- name: Check if we need to perform a reboot
  shell: dnf needs-restarting --reboothint
  register: reboot_required
  ignore_errors: True
  become: true

- name: Reboot the remote machine if updates occured
  reboot:
  when:
    - reboot_required.rc != 0
    - ansible_connection != "local"

- name: Reboot the local machine in 60s if updates occured
  shell: /bin/sleep 60; shutdown -r now "Ansible updates triggered"
  when:
    - reboot_required.rc != 0
    - ansible_connection == "local"

