---

# Use Cgroups v1 by default when on Fedora 31
# https://fedoraproject.org/wiki/Common_F31_bugs#Other_software_issues
- name: Read the kernel command line parameters
  shell: cat /proc/cmdline
  register: kernel_cmd
  become: true

# TODO: Not pretty. Move kernel param to it's own variable
- name: Add kernel param to switch to Cgroups v1
  shell: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
  when: ansible_facts['distribution_major_version'] == '31' and
        kernel_cmd.stdout.find('systemd.unified_cgroup_hierarchy') == -1 or
        kernel_cmd.stdout.find('systemd.unified_cgroup_hierarchy=1') != -1
  become: true
