---

dockerhub_img: roottjnii/interview-container
dockerhub_img_tag: 201805 

docker_host_username: docker # Container ran under this user
docker_host_group: docker # This is the default provided by Docker. This shouldn't be touched

docker_dnf_repo_url: https://download.docker.com/linux/fedora/docker-ce.repo
docker_dnf_repo_gpg: https://download.docker.com/linux/fedora/gpg

docker_container_port: 4567 # Port that is exposed to the host
docker_host_port: 4567 # Port that is exposed to the outside world

docker_container_service_name: docker.mauve
docker_container_service_restart_timeout: 10s
docker_container_service_path: '/etc/systemd/system/{{ docker_container_service_name }}.service'
docker_container_start_cmd: '/usr/bin/docker run --rm --publish {{ docker_host_port }}:{{ docker_container_port }} --name %n {{ dockerhub_img }}:{{ dockerhub_img_tag }}'
docker_container_start_pre_cmd: '-/usr/bin/docker rm --force %n' # If you prepend the path with a dash the result will be ignored
docker_container_stop_cmd: '-/usr/bin/docker container stop %n'
